// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\lorenz_model\Lorenz_FP_ip_src_Subsystem2.v
// Created: 2019-05-03 13:00:03
// 
// Generated by MATLAB 9.4 and HDL Coder 3.12
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Lorenz_FP_ip_src_Subsystem2
// Source Path: lorenz_model/Lorenz_FPGA_system/Subsystem2
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Lorenz_FP_ip_src_Subsystem2
          (clk,
           reset,
           enb,
           u,
           reset_1,
           u0,
           Out1);


  input   clk;
  input   reset;
  input   enb;
  input   signed [26:0] u;  // sfix27_En20
  input   reset_1;
  input   signed [26:0] u0;  // sfix27_En20
  output  signed [26:0] Out1;  // sfix27_En20


  wire signed [26:0] Switch1_out1;  // sfix27_En20
  wire signed [26:0] Saturation_out1;  // sfix27_En20
  wire signed [26:0] Add_out1;  // sfix27_En20
  reg signed [26:0] Unit_Delay2_out1;  // sfix27_En20
  wire signed [26:0] y;  // sfix27_En20

  // An Forward-Euler integrator with level-reset


  assign Switch1_out1 = (reset_1 == 1'b0 ? u :
              u0);



  assign Add_out1 = Switch1_out1 + Saturation_out1;



  always @(posedge clk or posedge reset)
    begin : Unit_Delay2_process
      if (reset == 1'b1) begin
        Unit_Delay2_out1 <= 27'sb000000000000000000000000000;
      end
      else begin
        if (enb) begin
          Unit_Delay2_out1 <= Add_out1;
        end
      end
    end



  assign y = (reset_1 == 1'b0 ? Unit_Delay2_out1 :
              u0);



  assign Saturation_out1 = (y > 27'sb011111100000000000000000000 ? 27'sb011111100000000000000000000 :
              (y < 27'sb100000100000000000000000000 ? 27'sb100000100000000000000000000 :
              y));



  assign Out1 = Saturation_out1;

endmodule  // Lorenz_FP_ip_src_Subsystem2

