ASFLAGS_ADDITIONAL = 
ALTERASOCEDSINSTALLDIR = C:/INTELF~2/17.0/embedded/ds-5/sw/gcc/bin
TARGET_SYSROOT = C:/PROGRA~3/MATLAB/SUPPOR~1/R2018a/3P778C~1.INS/ALTERA~1.INS/sysroot
TARGET_LOAD_CMD = 
TARGET_LOAD_CMD_ARGS = 
TARGET_PKG_INSTALLDIR = C:/PROGRA~3/MATLAB/SUPPOR~1/R2018a/toolbox/target/SUPPOR~1/ALTERA~1
STACK_SIZE = 64
