// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\lorenz_model\Subsystem_ip_addr_decoder.v
// Created: 2019-05-03 14:53:06
// 
// Generated by MATLAB 9.4 and HDL Coder 3.12
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Subsystem_ip_addr_decoder
// Source Path: Subsystem_ip/Subsystem_ip_axi4/Subsystem_ip_addr_decoder
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Subsystem_ip_addr_decoder
          (clk,
           reset,
           data_write,
           addr_sel,
           wr_enb,
           rd_enb,
           read_ip_timestamp,
           read_z,
           read_y,
           read_x,
           data_read,
           write_axi_enable,
           write_CLK,
           write_RST);


  input   clk;
  input   reset;
  input   [31:0] data_write;  // ufix32
  input   [13:0] addr_sel;  // ufix14
  input   wr_enb;  // ufix1
  input   rd_enb;  // ufix1
  input   [31:0] read_ip_timestamp;  // ufix32
  input   signed [26:0] read_z;  // sfix27_En20
  input   signed [26:0] read_y;  // sfix27_En20
  input   signed [26:0] read_x;  // sfix27_En20
  output  [31:0] data_read;  // ufix32
  output  write_axi_enable;  // ufix1
  output  write_CLK;  // ufix1
  output  write_RST;  // ufix1


  wire enb;
  wire decode_sel_ip_timestamp;  // ufix1
  wire const_1;  // ufix1
  wire decode_sel_x;  // ufix1
  wire decode_sel_y;  // ufix1
  wire decode_sel_z;  // ufix1
  wire [31:0] const_0;  // ufix32
  reg [31:0] read_reg_ip_timestamp;  // ufix32
  wire [31:0] decode_rd_ip_timestamp;  // ufix32
  reg signed [26:0] read_reg_z;  // sfix27_En20
  wire [31:0] data_in_z;  // ufix32
  wire [31:0] decode_rd_z;  // ufix32
  reg signed [26:0] read_reg_y;  // sfix27_En20
  wire [31:0] data_in_y;  // ufix32
  wire [31:0] decode_rd_y;  // ufix32
  reg signed [26:0] read_reg_x;  // sfix27_En20
  wire [31:0] data_in_x;  // ufix32
  wire [31:0] decode_rd_x;  // ufix32
  wire decode_sel_axi_enable;  // ufix1
  wire reg_enb_axi_enable;  // ufix1
  wire data_in_axi_enable;  // ufix1
  reg  write_reg_axi_enable;  // ufix1
  wire decode_sel_CLK;  // ufix1
  wire reg_enb_CLK;  // ufix1
  wire data_in_CLK;  // ufix1
  reg  write_reg_CLK;  // ufix1
  wire decode_sel_RST;  // ufix1
  wire reg_enb_RST;  // ufix1
  wire data_in_RST;  // ufix1
  reg  write_reg_RST;  // ufix1


  assign decode_sel_ip_timestamp = addr_sel == 14'b00000000000010;



  assign const_1 = 1'b1;



  assign enb = const_1;

  assign decode_sel_x = addr_sel == 14'b00000001000010;



  assign decode_sel_y = addr_sel == 14'b00000001000001;



  assign decode_sel_z = addr_sel == 14'b00000001000000;



  assign const_0 = 32'b00000000000000000000000000000000;



  always @(posedge clk or posedge reset)
    begin : reg_ip_timestamp_process
      if (reset == 1'b1) begin
        read_reg_ip_timestamp <= 32'b00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          read_reg_ip_timestamp <= read_ip_timestamp;
        end
      end
    end



  assign decode_rd_ip_timestamp = (decode_sel_ip_timestamp == 1'b0 ? const_0 :
              read_reg_ip_timestamp);



  always @(posedge clk or posedge reset)
    begin : reg_z_process
      if (reset == 1'b1) begin
        read_reg_z <= 27'sb000000000000000000000000000;
      end
      else begin
        if (enb) begin
          read_reg_z <= read_z;
        end
      end
    end



  assign data_in_z = {{5{read_reg_z[26]}}, read_reg_z};



  assign decode_rd_z = (decode_sel_z == 1'b0 ? decode_rd_ip_timestamp :
              data_in_z);



  always @(posedge clk or posedge reset)
    begin : reg_y_process
      if (reset == 1'b1) begin
        read_reg_y <= 27'sb000000000000000000000000000;
      end
      else begin
        if (enb) begin
          read_reg_y <= read_y;
        end
      end
    end



  assign data_in_y = {{5{read_reg_y[26]}}, read_reg_y};



  assign decode_rd_y = (decode_sel_y == 1'b0 ? decode_rd_z :
              data_in_y);



  always @(posedge clk or posedge reset)
    begin : reg_x_process
      if (reset == 1'b1) begin
        read_reg_x <= 27'sb000000000000000000000000000;
      end
      else begin
        if (enb) begin
          read_reg_x <= read_x;
        end
      end
    end



  assign data_in_x = {{5{read_reg_x[26]}}, read_reg_x};



  assign decode_rd_x = (decode_sel_x == 1'b0 ? decode_rd_y :
              data_in_x);



  assign data_read = decode_rd_x;

  assign decode_sel_axi_enable = addr_sel == 14'b00000000000001;



  assign reg_enb_axi_enable = decode_sel_axi_enable & wr_enb;



  assign data_in_axi_enable = data_write[0];



  always @(posedge clk or posedge reset)
    begin : reg_axi_enable_process
      if (reset == 1'b1) begin
        write_reg_axi_enable <= 1'b1;
      end
      else begin
        if (enb && reg_enb_axi_enable) begin
          write_reg_axi_enable <= data_in_axi_enable;
        end
      end
    end



  assign write_axi_enable = write_reg_axi_enable;

  assign decode_sel_CLK = addr_sel == 14'b00000001000011;



  assign reg_enb_CLK = decode_sel_CLK & wr_enb;



  assign data_in_CLK = data_write[0];



  always @(posedge clk or posedge reset)
    begin : reg_CLK_process
      if (reset == 1'b1) begin
        write_reg_CLK <= 1'b0;
      end
      else begin
        if (enb && reg_enb_CLK) begin
          write_reg_CLK <= data_in_CLK;
        end
      end
    end



  assign write_CLK = write_reg_CLK;

  assign decode_sel_RST = addr_sel == 14'b00000001000100;



  assign reg_enb_RST = decode_sel_RST & wr_enb;



  assign data_in_RST = data_write[0];



  always @(posedge clk or posedge reset)
    begin : reg_RST_process
      if (reset == 1'b1) begin
        write_reg_RST <= 1'b0;
      end
      else begin
        if (enb && reg_enb_RST) begin
          write_reg_RST <= data_in_RST;
        end
      end
    end



  assign write_RST = write_reg_RST;

endmodule  // Subsystem_ip_addr_decoder

