// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\hdlcoder_led_blinking\led_count_ip_dut.v
// Created: 2019-05-03 13:50:46
// 
// Generated by MATLAB 9.4 and HDL Coder 3.12
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: led_count_ip_dut
// Source Path: led_count_ip/led_count_ip_dut
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module led_count_ip_dut
          (clk,
           reset,
           dut_enable,
           Blink_frequency,
           Blink_direction,
           ce_out,
           LED,
           Read_back);


  input   clk;
  input   reset;
  input   dut_enable;  // ufix1
  input   [3:0] Blink_frequency;  // ufix4
  input   Blink_direction;  // ufix1
  output  ce_out;  // ufix1
  output  [7:0] LED;  // ufix8
  output  [7:0] Read_back;  // ufix8


  wire enb;
  wire ce_out_sig;  // ufix1
  wire [7:0] LED_sig;  // ufix8
  wire [7:0] Read_back_sig;  // ufix8


  assign enb = dut_enable;

  led_count_ip_src_led_counter u_led_count_ip_src_led_counter (.clk(clk),
                                                               .clk_enable(enb),
                                                               .reset(reset),
                                                               .Blink_frequency(Blink_frequency),  // ufix4
                                                               .Blink_direction(Blink_direction),  // ufix1
                                                               .ce_out(ce_out_sig),  // ufix1
                                                               .LED(LED_sig),  // ufix8
                                                               .Read_back(Read_back_sig)  // ufix8
                                                               );

  assign ce_out = ce_out_sig;

  assign LED = LED_sig;

  assign Read_back = Read_back_sig;

endmodule  // led_count_ip_dut

