// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\lorenz_model\Lorenz_FP_ip_dut.v
// Created: 2019-05-03 13:00:14
// 
// Generated by MATLAB 9.4 and HDL Coder 3.12
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Lorenz_FP_ip_dut
// Source Path: Lorenz_FP_ip/Lorenz_FP_ip_dut
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Lorenz_FP_ip_dut
          (clk,
           reset,
           dut_enable,
           RST,
           ce_out,
           x,
           y,
           z);


  input   clk;
  input   reset;
  input   dut_enable;  // ufix1
  input   RST;  // ufix1
  output  ce_out;  // ufix1
  output  signed [26:0] x;  // sfix27_En20
  output  signed [26:0] y;  // sfix27_En20
  output  signed [26:0] z;  // sfix27_En20


  wire enb;
  wire ce_out_sig;  // ufix1
  wire signed [26:0] x_sig;  // sfix27_En20
  wire signed [26:0] y_sig;  // sfix27_En20
  wire signed [26:0] z_sig;  // sfix27_En20


  assign enb = dut_enable;

  Lorenz_FP_ip_src_Lorenz_FPGA_system u_Lorenz_FP_ip_src_Lorenz_FPGA_system (.clk(clk),
                                                                             .clk_enable(enb),
                                                                             .reset(reset),
                                                                             .RST(RST),  // ufix1
                                                                             .ce_out(ce_out_sig),  // ufix1
                                                                             .x(x_sig),  // sfix27_En20
                                                                             .y(y_sig),  // sfix27_En20
                                                                             .z(z_sig)  // sfix27_En20
                                                                             );

  assign ce_out = ce_out_sig;

  assign x = x_sig;

  assign y = y_sig;

  assign z = z_sig;

endmodule  // Lorenz_FP_ip_dut

