// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\lorenz_model\Subsystem_ip_src_Subsystem.v
// Created: 2019-05-08 12:58:04
// 
// Generated by MATLAB 9.4 and HDL Coder 3.12
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 0.0005
// Target subsystem base rate: 0.0005
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        0.0005
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// x                             ce_out        0.0005
// y                             ce_out        0.0005
// z                             ce_out        0.0005
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Subsystem_ip_src_Subsystem
// Source Path: lorenz_model/Subsystem
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Subsystem_ip_src_Subsystem
          (clk,
           reset,
           clk_enable,
           CLK_1,
           RST,
           sigma,
           dt,
           x0,
           rho,
           y0,
           beta,
           z0,
           RST1,
           ce_out,
           x,
           y,
           z);


  input   clk;
  input   reset;
  input   clk_enable;
  input   CLK_1;
  input   RST;
  input   signed [26:0] sigma;  // sfix27_En20
  input   signed [26:0] dt;  // sfix27_En20
  input   signed [26:0] x0;  // sfix27_En20
  input   signed [26:0] rho;  // sfix27_En20
  input   signed [26:0] y0;  // sfix27_En20
  input   signed [26:0] beta;  // sfix27_En20
  input   signed [26:0] z0;  // sfix27_En20
  input   RST1;
  output  ce_out;
  output  signed [26:0] x;  // sfix27_En20
  output  signed [26:0] y;  // sfix27_En20
  output  signed [26:0] z;  // sfix27_En20


  wire Logical_Operator_out1;
  wire signed [26:0] Triggered_Subsystem3_out1;  // sfix27_En20
  wire signed [26:0] Triggered_Subsystem3_out2;  // sfix27_En20
  wire signed [26:0] Triggered_Subsystem3_out3;  // sfix27_En20


  assign Logical_Operator_out1 = RST | RST1;



  Subsystem_ip_src_Triggered_Subsystem3 u_Triggered_Subsystem3 (.clk(clk),
                                                                .reset(reset),
                                                                .enb(clk_enable),
                                                                .RST(Logical_Operator_out1),
                                                                .sigma(sigma),  // sfix27_En20
                                                                .dt(dt),  // sfix27_En20
                                                                .x0(x0),  // sfix27_En20
                                                                .rho(rho),  // sfix27_En20
                                                                .y0(y0),  // sfix27_En20
                                                                .beta(beta),  // sfix27_En20
                                                                .z0(z0),  // sfix27_En20
                                                                .Trigger(CLK_1),
                                                                .x(Triggered_Subsystem3_out1),  // sfix27_En20
                                                                .y(Triggered_Subsystem3_out2),  // sfix27_En20
                                                                .z(Triggered_Subsystem3_out3)  // sfix27_En20
                                                                );

  assign x = Triggered_Subsystem3_out1;

  assign y = Triggered_Subsystem3_out2;

  assign z = Triggered_Subsystem3_out3;

  assign ce_out = clk_enable;

endmodule  // Subsystem_ip_src_Subsystem

